### PR TITLE
fix: game object can be deleted regardless of children

### LINKED ISSUE #249: Delete game object stopped working since merge with Hirearchy optimizations
Deleting a game object in the scene while in the editor throws and error from WindowHirearchy::Draw() function.
(There must be a null pointer in there somewhere to the deleted object)

(Sometimes it crashes sometimes it doesn't).

image

### PR DESCRIPTION
**Pull request by gerard-queralt**
Should fix #249

### CODE REVIEW

File: Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp [hunk 1]
```diff
@@ -270,9 +270,9 @@ void WindowHierarchy::DrawRecursiveHierarchy(GameObject* gameObject)
 
     if (nodeDrawn) // If the parent node is correctly drawn, draw its children
     {
-        for (int i = 0; i < children.size(); ++i)
+        for (GameObject* child : gameObject->GetChildren())
```
Comment (markmeliaa) [inline Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp:273]: Which is the difference between the former way using an additional vector `children` and this way?

Comment (gerard-queralt) [reply Source/DataModels/Windows/EditorWindows/WindowHierarchy.cpp]: While what I said is correct, @DADSILVER let me know that `GetChildren` is one of the most expensive things done in the Hierarchy window, so it's noticeably better to call it only once ^^'

**Review by gerard-queralt — COMMENTED** [review]
I can't approve the pull request since I'm the author, but thank you David for finding a better solution than mine!

**Review by markmeliaa — APPROVED** [review]

**Review by PaablooCH — APPROVED** [review]
